<x-guest-layout>
    <div class="mb-6"><p class="page-kicker">Nueva cuenta</p><h1 class="mt-1 text-2xl font-bold text-slate-900">Regístrate en LexBot AI</h1><p class="mt-2 text-sm leading-6 text-slate-500">Crea una cuenta de cliente o abogado. Las cuentas administrativas se gestionan internamente.</p></div>
    <form method="POST" action="{{ route('register') }}" class="space-y-5">@csrf
        <div><x-input-label for="nombre" value="Nombre completo" /><x-text-input id="nombre" class="mt-2 block w-full rounded-xl" type="text" name="nombre" :value="old('nombre')" required autofocus autocomplete="name" /><x-input-error :messages="$errors->get('nombre')" class="mt-2" /></div>
        <div><x-input-label for="email" value="Correo electrónico" /><x-text-input id="email" class="mt-2 block w-full rounded-xl" type="email" name="email" :value="old('email')" required autocomplete="username" /><x-input-error :messages="$errors->get('email')" class="mt-2" /></div>
        <div><x-input-label for="rol" value="Tipo de cuenta" /><select id="rol" name="rol" class="mt-2 block w-full rounded-xl border-slate-300" required><option value="cliente" @selected(old('rol', 'cliente') === 'cliente')>Cliente</option><option value="abogado" @selected(old('rol') === 'abogado')>Abogado</option></select><p class="mt-2 text-xs leading-5 text-slate-500">Los abogados completan su especialidad al ingresar por primera vez.</p><x-input-error :messages="$errors->get('rol')" class="mt-2" /></div>
        <div><x-input-label for="password" value="Contraseña" /><x-text-input id="password" class="mt-2 block w-full rounded-xl" type="password" name="password" required autocomplete="new-password" /><x-input-error :messages="$errors->get('password')" class="mt-2" /></div>
        <div><x-input-label for="password_confirmation" value="Confirmar contraseña" /><x-text-input id="password_confirmation" class="mt-2 block w-full rounded-xl" type="password" name="password_confirmation" required autocomplete="new-password" /><x-input-error :messages="$errors->get('password_confirmation')" class="mt-2" /></div>
        <div class="flex flex-col gap-3 pt-1 sm:flex-row sm:items-center sm:justify-between"><a class="text-sm font-semibold text-blue-700 hover:text-blue-800" href="{{ route('login') }}">Ya tengo una cuenta</a><x-primary-button class="justify-center rounded-xl !bg-blue-700 !px-5 !py-3 !text-sm !normal-case !tracking-normal hover:!bg-blue-800">Crear cuenta</x-primary-button></div>
    </form>
</x-guest-layout>
